//! GOAL-B station 3 — the Rust half of the flame seam on the *production*
//! artifact: `tables/chem/lox_lh2_v0.1.0.h5`, generated by NASA CEA through
//! `offline/crucible_offl/surfaces.py` (regenerable via
//! `offline/scripts/make_station3_tables.py`), loaded here through the full
//! FND-5 §3.2 pin gate and interpolated by the runtime path SOLV-1 will use.
//!
//! Pins must match `tables/chem/lox_lh2_v0.1.0.pins.toml` (the FND-4 §6-4
//! config wiring consumes them when it lands). Reference interpolation
//! values come from the Python reference evaluator over the same file —
//! asserted to 1e-6 abs so the two runtimes provably interpolate the same
//! surface the same way; the physics anchors (CEA direct solves) sit
//! within the certificate's gas-region error analysis.

use crucible_tables::{Pin, Table, TableError};

const FILE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tables/chem/lox_lh2_v0.1.0.h5"
);
const DATA_VERSION: &str = "0.1.0";
const EQ_DIGEST: &str = "sha256:b6793b344396d28355cc08799f9ba68434b50ddf87dee4655d6b25d6e7ce2c37";
const PERF_DIGEST: &str = "sha256:9dfc705e250b0f91a538285d76dd2dfef479c14050bdf767a641b68a2441d8dc";

// The RL10-class chamber point: p_c = 32.75 bar, MR = 5 (Z = 1/6), h at
// the liquid-injection enthalpy (H2(L) 20.27 K / O2(L) 90.17 K, CEA).
const P_C: f64 = 32.75e5;
const H_INJ: f64 = -1083091.499726406;
const Z: f64 = 1.0 / 6.0;
// CEA direct HP solve at that point (the truth the surface tabulates).
const T_CHAMBER_CEA: f64 = 3225.4141325483242;

fn pin(digest: &str) -> Pin {
    Pin {
        data_version: DATA_VERSION.into(),
        content_digest: Some(digest.into()),
    }
}

#[test]
fn equilibrium_surface_loads_and_reproduces_the_rl10_chamber() {
    let t = Table::open(FILE, "/chem/lox_lh2/equilibrium", &pin(EQ_DIGEST))
        .expect("production equilibrium surface must load under its pin");
    assert_eq!(t.axes.len(), 3);
    assert_eq!(t.values.len(), 12);

    let temp = t
        .interpolate("temperature", &[P_C, H_INJ, Z])
        .expect("chamber point is in-envelope");
    // Cross-language interpolation identity (Python reference evaluator).
    assert!(
        (temp - 3224.9980897936157).abs() < 1e-6,
        "Rust multilinear must reproduce the reference interpolation, got {temp}"
    );
    // Physics: the interpolated flame temperature is the CEA chamber
    // solution to well inside the gas-region error analysis (±1 K here;
    // the stored full-envelope bound is kink-dominated and much larger).
    assert!(
        (temp - T_CHAMBER_CEA).abs() < 1.0,
        "interpolated chamber T {temp} vs CEA {T_CHAMBER_CEA}"
    );

    let gamma = t
        .interpolate("gamma_eff", &[P_C, H_INJ, Z])
        .expect("in-envelope");
    assert!((gamma - 1.1513950956743837).abs() < 1e-9);
    let a = t
        .interpolate("sound_speed", &[P_C, H_INJ, Z])
        .expect("in-envelope");
    assert!((a - 1620.8340431597053).abs() < 1e-6);
}

#[test]
fn performance_reference_loads_and_interpolates_c_star() {
    let t = Table::open(FILE, "/chem/lox_lh2/performance", &pin(PERF_DIGEST))
        .expect("production performance reference must load under its pin");
    let c_star = t
        .interpolate("c_star_ideal", &[P_C, 5.0])
        .expect("in-envelope");
    assert!((c_star - 2362.4816141932856).abs() < 1e-6);
    // CEA's direct rocket solve at this point gives c* = 2362.531 m/s;
    // the interpolant sits within the stored bound (±1.8 m/s).
    assert!((c_star - 2362.531).abs() < 1.8);
}

#[test]
fn units_bind_gate_refuses_a_relabeled_column() {
    // META-2 §4 ★ at the seam: the consumer declares what units it expects
    // at bind time; a mismatch is a refusal, never a misread quantity.
    let t = Table::open(FILE, "/chem/lox_lh2/equilibrium", &pin(EQ_DIGEST)).expect("load");
    t.expect_units("temperature", "K").expect("declared in K");
    t.expect_units("sound_speed", "m/s")
        .expect("declared in m/s");
    match t.expect_units("temperature", "Pa") {
        Err(TableError::UnitsMismatch {
            expected, found, ..
        }) => {
            assert_eq!(expected, "Pa");
            assert_eq!(found, "K");
        }
        other => panic!("expected UnitsMismatch, got {other:?}"),
    }
}

#[test]
fn out_of_envelope_refuses_never_extrapolates() {
    let t = Table::open(FILE, "/chem/lox_lh2/equilibrium", &pin(EQ_DIGEST)).expect("load");
    // p below the declared envelope (but still above the grid floor).
    match t.interpolate("temperature", &[1.6e3, H_INJ, Z]) {
        Err(TableError::OutOfEnvelope { axis, .. }) => assert_eq!(axis, "p"),
        other => panic!("expected OutOfEnvelope on p, got {other:?}"),
    }
    // Z beyond the envelope (grid reaches 0.26, envelope stops at 0.25).
    match t.interpolate("temperature", &[P_C, H_INJ, 0.255]) {
        Err(TableError::OutOfEnvelope { axis, .. }) => assert_eq!(axis, "Z"),
        other => panic!("expected OutOfEnvelope on Z, got {other:?}"),
    }
}
